const swaggerAutogen = require('swagger-autogen')();
const outputFile = './config/swagger_output.json';
const endpointsFiles = ['./routes/*.js'];

const doc = {
  info: {
    title: 'API Documentation',
    description: 'API Documentation automatically generated by swagger-autogen',
  },
  host: 'localhost:8000',
  schemes: ['http'],
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  console.log("Swagger file generated successfully.");
});
